services:
  db:
    image: postgres:16-alpine
    container_name: movierate_db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/script.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./backend
    container_name: movierate_backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      PORT: '3001'
      DB_HOST: db
    ports:
      - '3001:3001'
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: movierate_frontend
    restart: unless-stopped
    env_file:
      - ./frontend/.env
    environment:
      - API_URL_SERVER=http://backend:3001
    ports:
      - '3000:3000'
    depends_on:
      - backend

volumes:
  postgres_data:
